#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Mar 27 07:58:53 +07 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 602d8fc5f1344335a6c84953e71e2027 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot Floating_Point_RGBtoHSV_testbench_func_synth xil_defaultlib.Floating_Point_RGBtoHSV_testbench xil_defaultlib.glbl -log elaborate.log"
xelab -wto 602d8fc5f1344335a6c84953e71e2027 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot Floating_Point_RGBtoHSV_testbench_func_synth xil_defaultlib.Floating_Point_RGBtoHSV_testbench xil_defaultlib.glbl -log elaborate.log

