#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Apr 03 00:57:32 +07 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 0697f38dd9c343d69860351fbe5a97fb --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot Floating_Point_RGBtoHSV_testbench_behav xil_defaultlib.Floating_Point_RGBtoHSV_testbench xil_defaultlib.glbl -log elaborate.log"
xelab -wto 0697f38dd9c343d69860351fbe5a97fb --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot Floating_Point_RGBtoHSV_testbench_behav xil_defaultlib.Floating_Point_RGBtoHSV_testbench xil_defaultlib.glbl -log elaborate.log

